##Abdulshaheed Alqunber
##ps9pr4

import random

def create_dictionary(filename):
    """takes a string representing the name of a text file,
    and returns a dictionary of key-value pairs in which:
    • each key is a word encountered in the text file
    • the corresponding value is a list of words that follow
      the key word in the text file
    """
    
    file = open(filename, 'r')
    text = file.read()
    file.close()
    words = text.split()
    d = {}
    current_word = '$'
    for next_word in words:
        if current_word not in d:
            d[current_word] = [next_word]
        else:
            d[current_word] += [next_word]
            
        if '.' in next_word or '?' in next_word or '!' in next_word:
            current_word = '$'
        else:
            current_word = next_word
            
    return d

def generate_text(word_dict, num_words):
    """takes as parameters a dictionary of word transitions
    (generated by the create_dictionary function) named word_dict
    and a positive integer named num_words. The function should use
    word_dict to generate and print a string of num_words words.
    """

    current_word = '$'
    for i in range(num_words):
        wordlist = word_dict[current_word]
        next_word = random.choice(wordlist)
        print(next_word, end=' ')
        if '.' in next_word or '?' in next_word or '!' in next_word:
            current_word = '$'
        else:
            current_word = next_word
    print()
    
